version: '3.8'
services:
  corporation-service:
    container_name: corporation-service
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      # - DB_HOST=host.docker.internal
      # - DB_PORT=1401
      - DB_HOST=db-final.cdublfjfuteq.ap-southeast-1.rds.amazonaws.com
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=abc@12345
      - DB_NAME=Corporation_Service_Db
      - REDIS_LOCAL_HOST=redis-cache
      - REDIS_LOCAL_PORT=6379
      - REDIS_LOCAL_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # depends_on:
    #   # - mssql-db
    #   - redis-cache
    ports:
      - 3000:3000
    restart: unless-stopped
    links:
      # - mssql-db
      - redis-cache
    mem_limit: 128m
    cpus: 0.2
    # networks:
    #   - development
  # mssql-db:
  #   container_name: mssql-db
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   volumes:
  #     - ~/apps/mssql/data:/var/lib/mssqlql/data
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=abc@12345
  #   healthcheck:
  #     test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ""$$SA_PASSWORD"" -Q "SELECT 1" || exit 1
  #     timeout: 45s
  #     interval: 10s
  #     retries: 10
  #   mem_limit: 1Gb
  #   cpus: 0.2
  #   ports:
  #     - 1401:1433
  #   networks:
  #     - development
  redis-cache:
    container_name: redis-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-cache:/data
    # networks:
    #   - development

# networks:
#   development:
#     driver: bridge
volumes:
  # mssql-db:
  #   driver: local
  redis-cache:
    driver: local
